## Exercise_2
**Build a machine learning model to decide salaries for future candidates. Using this predict salaries for following candidates:**

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

In [1]:
import warnings
warnings.filterwarnings('ignore')

## Import needed modules

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
# reading data
data = pd.read_csv("hiring.csv")
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
# filling missing data with zero
data.experience = data.experience.fillna("zero")
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
# Import word2number module to convert string data to numerical data
from word2number import w2n

In [6]:
data.experience = data.experience.apply(w2n.word_to_num)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [7]:
# replace numeric value (test_score(out of 10)) missing with median
data['test_score(out of 10)'].median()

8.0

In [8]:
data['test_score(out of 10)'].fillna(data['test_score(out of 10)'].median(), inplace=True)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [9]:
# making experience, test_score(out of 10) and interview_score(out of 10) as a feature (x)
x = data.drop('salary($)', axis='columns')
x

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    8.0                           7
7          11                    7.0                           8

In [10]:
# making salary($) as a feature (y)
y = data['salary($)']
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [11]:
# creating a model
model = LinearRegression()

In [12]:
# fitting data to train the model
model.fit(x, y)

LinearRegression()

## Making prediction

In [13]:
# making prediction for 5 yr experience, 6 test score and 7 interview score  
model.predict([[5, 6, 7]])

array([58312.95487627])

In [14]:
# making prediction for  2 yr experience, 9 test score and 6 interview score
model.predict([[2, 9, 6]])

array([53205.96797671])

In [15]:
# making prediction for  12 yr experience, 10 test score and 10 interview score
model.predict([[12, 10, 10]])

array([92002.18340611])

## To calculate accuracu

In [16]:
model.score(x, y)

0.9616780002577959