## Exercise_2
**Build a machine learning model to decide salaries for future candidates. Using this predict salaries for following candidates:

**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**

## Import needed modules

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
# reading data
data = pd.read_csv("hiring.csv")
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
# transforming experience into numerical data from 1 to 11
def trans_experience(x):
    if x == 'one' :
        return 1
    if x == 'two' :
        return 2
    if x == 'three' :
        return 3
    if x == 'four' :
        return 4
    if x == 'five' :
        return 5
    if x == 'six' :
        return 6
    if x == 'seven' :
        return 7
    if x == 'eight' :
        return 8
    if x == 'nine' :
        return 9
    if x == 'ten' :
        return 10
    if x == 'eleven' :
        return 11

In [7]:
data['trans_experience'] = data['experience'].apply(trans_experience)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0        NaN                    8.0                           9      50000   
1        NaN                    8.0                           6      45000   
2       five                    6.0                           7      60000   
3        two                   10.0                          10      65000   
4      seven                    9.0                           6      70000   
5      three                    7.0                          10      62000   
6        ten                    NaN                           7      72000   
7     eleven                    7.0                           8      80000   

   trans_experience  
0               NaN  
1               NaN  
2               5.0  
3               2.0  
4               7.0  
5               3.0  
6              10.0  
7              11.0

### Data Preprocessing: Fill NA values with median value of a column

In [8]:
# replace numeric value (trans_experience) missing with median
data.trans_experience.median()

6.0

In [9]:
data.trans_experience.fillna(data.trans_experience.median(), inplace=True)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0        NaN                    8.0                           9      50000   
1        NaN                    8.0                           6      45000   
2       five                    6.0                           7      60000   
3        two                   10.0                          10      65000   
4      seven                    9.0                           6      70000   
5      three                    7.0                          10      62000   
6        ten                    NaN                           7      72000   
7     eleven                    7.0                           8      80000   

   trans_experience  
0               6.0  
1               6.0  
2               5.0  
3               2.0  
4               7.0  
5               3.0  
6              10.0  
7              11.0

In [14]:
# replace numeric value (test_score(out of 10)) missing with median
data['test_score(out of 10)'].median()

8.0

In [15]:
data['test_score(out of 10)'].fillna(data['test_score(out of 10)'].median(), inplace=True)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0        NaN                    8.0                           9      50000   
1        NaN                    8.0                           6      45000   
2       five                    6.0                           7      60000   
3        two                   10.0                          10      65000   
4      seven                    9.0                           6      70000   
5      three                    7.0                          10      62000   
6        ten                    8.0                           7      72000   
7     eleven                    7.0                           8      80000   

   trans_experience  
0               6.0  
1               6.0  
2               5.0  
3               2.0  
4               7.0  
5               3.0  
6              10.0  
7              11.0

In [16]:
# dropping experience column
new_data = data.drop('experience', axis = 1)
new_data

test_score(out of 10)  interview_score(out of 10)  salary($)  \
0                    8.0                           9      50000   
1                    8.0                           6      45000   
2                    6.0                           7      60000   
3                   10.0                          10      65000   
4                    9.0                           6      70000   
5                    7.0                          10      62000   
6                    8.0                           7      72000   
7                    7.0                           8      80000   

   trans_experience  
0               6.0  
1               6.0  
2               5.0  
3               2.0  
4               7.0  
5               3.0  
6              10.0  
7              11.0

In [17]:
# making test_score(out of 10), interview_score(out of 10) and trans_experience as a feature (x)
x = new_data.drop('salary($)', axis='columns')
x

test_score(out of 10)  interview_score(out of 10)  trans_experience
0                    8.0                           9               6.0
1                    8.0                           6               6.0
2                    6.0                           7               5.0
3                   10.0                          10               2.0
4                    9.0                           6               7.0
5                    7.0                          10               3.0
6                    8.0                           7              10.0
7                    7.0                           8              11.0

In [18]:
# making salary($) as a feature (y)
y = data['salary($)']
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [24]:
# creating a model
model = LinearRegression()

In [25]:
# fitting data to train the model
model.fit(x, y)

LinearRegression()

## Making prediction

In [28]:
# making prediction for 6 test score, 7 interview score and 5 yr experience
model.predict([[6, 7, 5]])

C:\Users\20155\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([54422.76422764])

In [29]:
# making prediction for 10 test score, 10 interview score and 2 yr experience
model.predict([[10, 10, 2]])

C:\Users\20155\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([60097.56097561])

In [31]:
# making prediction for 9 test score, 6 interview score and 2 yr experience
model.predict([[9, 6, 2]])

C:\Users\20155\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47056.91056911])

In [33]:
# making prediction for 10 test score, 10 interview score and 12 yr experience
model.predict([[10, 10, 12]])

C:\Users\20155\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88227.64227642])

## To calculate accuracy

In [34]:
model.score(x, y)

0.4000070238283375