## Import NumPy Library

In [1]:
import numpy as np

#### 1. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [4]:
a = np.zeros(10) # 1-D array of 10 zeros
b = np.ones(10)  # 1-D array of 10 ones
c = np.full((10), 5) # 1-D array of 10 fives
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


##### 2. Write a NumPy program to find the missing data in an array

In [22]:
array = np.array([[1,2,3,4],
             [np.nan, 5,6,7],
             [2,3,4,5],
             [1,2,3,np.nan]])

print("Values with missing data in array: \n", array)
print()
print("The missing data in an array: \n", np.isnan(array))

Values with missing data in array: 
 [[ 1.  2.  3.  4.]
 [nan  5.  6.  7.]
 [ 2.  3.  4.  5.]
 [ 1.  2.  3. nan]]

The missing data in an array: 
 [[False False False False]
 [ True False False False]
 [False False False False]
 [False False False  True]]


##### 3. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [23]:
vector = np.random.randint(0, 11, 5)
print("Vector values are: ", vector)

Vector values are:  [4 3 2 9 4]


##### 4. Write a NumPy program to create a 3x3 identity matrix,  diagonal elements are 1,the rest are 0.

In [24]:
iden_matrix = np.eye(3)
iden_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 5. Write a NumPy program to create a 3x4 matrix filled with values ​​from 10 to 21

In [25]:
matrix = np.arange(10, 22).reshape(3, 4)
matrix

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

#### 6. Write a NumPy program to generate a random number between 0 and 1.

In [30]:
num = np.random.normal(0, 1, 1)
print("Random number between 0 and 1 is: ", num)

Random number between 0 and 1 is:  [-0.33531679]


#### 7. Write a NumPy program to create an array of all the even integers from 30 to 70.

In [31]:
array = np.arange(30, 71, 2)
print("Even values between 30 and 70 are: ", array)

Even values between 30 and 70 are:  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### 8. Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [34]:
vector = np.arange(15, 55)
print("All values except the first and last are: \n", vector[1 : -1])

All values except the first and last are: 
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


#### 9. Write a NumPy program to sort an array by row and column in ascending order.

In [39]:
array = np.random.randint(-3,10,size=20).reshape((4,5))
print("Original array is: \n", array)
print()
print("array sorted br rows: \n", np.sort(array, axis = 1))
print()
print("array sorted br columns: \n", np.sort(array, axis = 0))

Original array is: 
 [[ 1  5  1  8  9]
 [ 9  6  8  9 -3]
 [ 6 -1  9  3 -3]
 [ 5  3 -3  7 -2]]

array sorted br rows: 
 [[ 1  1  5  8  9]
 [-3  6  8  9  9]
 [-3 -1  3  6  9]
 [-3 -2  3  5  7]]

array sorted br columns: 
 [[ 1 -1 -3  3 -3]
 [ 5  3  1  7 -3]
 [ 6  5  8  8 -2]
 [ 9  6  9  9  9]]


#### 10. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.

In [46]:
Three_D_array = np.zeros((3, 5, 4))
print("3D array with shape (3,5,4) is: \n", Three_D_array)

3D array with shape (3,5,4) is: 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
