## Import NumPy Library

In [1]:
import numpy as np

####  Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [8]:
array = np.ones((4, 4), dtype = "int32")
print("Original matrix is: \n", array)
print()
array[1:3, 1:3] = 0
new_array = array
print("New matrix is: \n", new_array)

Original matrix is: 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

New matrix is: 
 [[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


#### 2. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [16]:
matrix = np.zeros((8, 8), dtype = "int32")
print("Original matix is: \n", matrix)
print()
# to change values in rows 
matrix[1::2, ::2] = 1
# to change values in columns
matrix[::2, 1::2] = 1
print("Matix with checkerboard pattern is: \n", matrix)

Original matix is: 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Matix with checkerboard pattern is: 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 3. Write a NumPy program to find common values between two arrays

In [20]:
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
arr2 = np.array([10, 30, 50, 70, 90])
print("The first array = ", arr1)
print("The second array = ", arr2)
print("The common values between the two arrays are: ", np.intersect1d(arr1, arr2))

The first array =  [ 10  20  30  40  50  60  70  80  90 100]
The second array =  [10 30 50 70 90]
The common values between the two arrays are:  [10 30 50 70 90]


#### 4. Write a NumPy program to test whether each element of a 1-D array is also present in a second    array

In [22]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 30, 50])
print("array1 = ", arr1)
print("array2 = ", arr2)
print("The comparison between 2 arrays is: ", np.in1d(arr1, arr2))

array1 =  [10 20 30 40 50]
array2 =  [10 30 50]
The comparison between 2 arrays is:  [ True False  True False  True]


#### 5. Write a NumPy program compare two arrays.

In [30]:
arr1 = np.array([2, 4])
arr2 = np.array([0, 4])
print("First array = ", arr1)
print("Second array = ", arr2)
print()
print("First array is greater than  or equal second array: ", arr1 >= arr2)
print("First array is smaller than or equal second array: ", arr1 <= arr2)
print("First array is equal second array: ", arr1 == arr2)
print("First array is not equal second array: ", arr1 != arr2)

First array =  [2 4]
Second array =  [0 4]

First array is greater than  or equal second array:  [ True  True]
First array is smaller than or equal second array:  [False  True]
First array is equal second array:  [False  True]
First array is not equal second array:  [ True False]


#### 6. Write a Numpy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order

In [37]:
arr = np.arange(1, 15, dtype = "int32")
print("The original array is: ", arr)

# N split points lead to N + 1 subarrays
arr1, arr2, arr3 = np.split(arr, [2, 6])
print("The first subarray is: ", arr1)
print("The second subarray is: ", arr2)
print("The third subarray is: ", arr3)

The original array is:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The first subarray is:  [1 2]
The second subarray is:  [3 4 5 6]
The third subarray is:  [ 7  8  9 10 11 12 13 14]


#### 7. Write a NumPy program to create a 5x5x5.

In [38]:
array = np.ones((5, 5, 5), dtype=int)
array

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 8. Write a NumPy program to access an array by column.

In [51]:
array = np.arange(1, 26).reshape(5, 5)
print("The original array is: \n", array, "\n")
print("The first column is: \n", array[:, 0].reshape(5, 1), "\n")
print("The second column is: \n", array[:, 1].reshape(5, 1), "\n")
print("The third column is: \n", array[:, 2].reshape(5, 1), "\n")
print("The fourth column is: \n", array[:, 3].reshape(5, 1), "\n")
print("The fifth column is: \n", array[:, 4].reshape(5, 1), "\n")

The original array is: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

The first column is: 
 [[ 1]
 [ 6]
 [11]
 [16]
 [21]] 

The second column is: 
 [[ 2]
 [ 7]
 [12]
 [17]
 [22]] 

The third column is: 
 [[ 3]
 [ 8]
 [13]
 [18]
 [23]] 

The fourth column is: 
 [[ 4]
 [ 9]
 [14]
 [19]
 [24]] 

The fifth column is: 
 [[ 5]
 [10]
 [15]
 [20]
 [25]] 



#### 9. Write a NumPy program to replace the negative values in a NumPy array with 0

In [53]:
array = np.array([-3, 4, -1, 2, 3, -5, 10])
print("The original array = ", array)
array[array < 0] = 0
print("array after replacement = ", array)

The original array =  [-3  4 -1  2  3 -5 10]
array after replacement =  [ 0  4  0  2  3  0 10]


#### 10. Write a NumPy program to stack arrays in sequence vertically.

In [62]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = np.arange(10, 19).reshape(3, 3)
print("The first array: \n", arr1, "\n")
print("The second array: \n", arr2, "\n")
arr3 = np.vstack([arr1, arr2])
print("The final array after stack 2 arrays: \n", arr3 )

The first array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

The second array: 
 [[10 11 12]
 [13 14 15]
 [16 17 18]] 

The final array after stack 2 arrays: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
